name: Build and Deploy to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Log in to the Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: cookingrecipesregistry.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
          
      - name: Build and push the Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: cookingrecipesregistry.azurecr.io/cookingrecipesapi:${{ github.sha }}
          file: Dockerfile
          context: .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: cooking-recipes-api
          images: cookingrecipesregistry.azurecr.io/cookingrecipesapi:${{ github.sha }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
