# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - cooking-recipes-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_02bc2e08de734bda9be5912a615aa18e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_1338c302b0ef4369b418be4f37e54455 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_02bc2e08de734bda9be5912a615aa18e }}/cookingrecipesregistry.azurecr.io/cookingrecipesapi:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'cooking-recipes-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_810580b90db54342b70f234dc7ea96c0 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_02bc2e08de734bda9be5912a615aa18e }}/cookingrecipesregistry.azurecr.io/cookingrecipesapi:${{ github.sha }}'